### ISSUE TITLE
Hello can you add i18n

### ISSUE THREAD

**Issue by villers** [EvgeniyKumachev/nextjs-react-boilerplate#1]
i want use i18n for translation and intl for format number? how can i do it?
i have another question. How use getInitialProps in page?

**Comment by EvgeniyKumachev** [comment]
Right now i can't think any nice way of putting intl and i18n together in a single branch, but you can use [this example](https://github.com/zeit/next.js/tree/v3-beta/examples/with-react-i18next) to tweak it.

As of getInitialProps in page i've looked into it and will fix it when i have time

**Comment by EvgeniyKumachev** [comment]
Fixed problem with `getInitialProps()` and added example in `pages/index.js`
https://github.com/EvgeniyKumachev/nextjs-react-boilerplate/commit/be46f06deb6ade76ee2006a319118fc6e2e8141e
